appwebserver:
 build: .
 ports:
  - "80:80"
 links:
  - db:mysql

db:
 image: mysql:5.6
 environment:
  MYSQL_ROOT_PASSWORD: 123456
  MYSQL_DATABASE: worldapi
  MYSQL_USER: devspark
  MYSQL_PASSWORD: dev123